# -*- coding: utf-8 -*-
"""protect-yolo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hUea5TGXQquMIKVfJ8_8nqnqEKbaebQv
"""

!pip install ultralytics

from ultralytics import YOLO

model = YOLO('yolov8n.pt')
results = model('/content/drive/MyDrive/Colab Notebooks/1722855664066.jpg')

for result in results:
  boxes = result.boxes
  result.save(filename='result.jpg')

import matplotlib.pyplot as plt
import matplotlib.image as mpimg

img = '/content/result.jpg'

image = mpimg.imread(img)
plt.imshow(image)
plt.axis('off')
plt.show()